---
- include: packages.yaml
- include: user.yaml
- include: rvm.yaml
- include: source.yaml
- include: config.yaml
- include: ruby.yaml
- include: bundler.yaml
- name: Configure database
  include_tasks: database.yaml
  when: db_setup_database
- include: assets.yaml
- include: init.yaml
- include: apache.yaml
- include: backups.yaml
  when: diaspora_backups_copypath is defined
- include: monitoring.yaml
