---
# Ubuntu 14.04 has some weird locale issues, make sure some things are set
# Otherwise postgres will fail to init properly
- name: Locale patch for postgres
  lineinfile: dest=/etc/default/locale line='LANGUAGE="en_US:en"' state=present
  when: db_setup_database
- name: Locale patch for postgres
  lineinfile: dest=/etc/default/locale line='LC_ALL="en_US.UTF-8"' state=present
  when: db_setup_database

- name: System dependencies - Ubuntu
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - apache2
    - build-essential
    - git
    - curl
    - imagemagick
    - libmagickwand-dev
    - redis-server
    - libcurl4-openssl-dev
    - libxml2-dev
    - libxslt-dev
    - libpq-dev
    - python-psycopg2
    # Monitoring
    - python3-psutil

- name: Install postgres
  apt: name={{ item }} state=present
  with_items:
    - postgresql
  when: db_setup_database
