---
- name: RVM gpg key
  shell: /usr/bin/gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  become: yes
  become_user: "{{ os_user }}"
- name: Install RVM
  shell: /usr/bin/curl -L https://s.diaspora.software/1t | bash
  become: yes
  become_user: "{{ os_user }}"
- name: RVM in .bashrc
  lineinfile: dest=/home/{{ os_user }}/.bashrc state=present line='[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"'
