---
- name: Diaspora user
  user: name={{ os_user }} state=present
- name: Ensure www-data member of diaspora group
  user: name=www-data append=yes groups={{ os_user }} state=present
- name: Make Diaspora home non-world readable
  file: path=/home/{{ os_user }} mode=0750 state=directory
